
- name: 'Check for {{ gi_home_inventory }} in inventory.xml'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  shell:  |
    grep '{{ gi_home_inventory }}' {{ inventory_path }}/ContentsXML/inventory.xml
  ignore_errors: '{{ ignore_errors_flag }}'
  register: 'home_path_result'
- debug: { msg: 'home_path_result' }