
- name: 'Register RDBMS Image {{ image_name }}'
  include_role:
    name: 'fpp_common'
    tasks_from: 'image_register.yml'
  vars:
    image_map: 'db/{{ image_name }}.map'
    software_type: 'ORACLEDBSOFTWARE'

- name: 'Query RDBMS Image {{ image_name }}'
  include_role:
    name: 'fpp_common'
    tasks_from: 'image_query.yml'