
- name: 'Discover VM Cluster for DB Home {{ db_home_name }}'
  when: compartment_id is not defined
  include_tasks: '{{ exadata_type }}_vm_cluster_discovery.yml'

- assert: { that: compartment_id is defined }

# Create new database home. Default Source is VM_CLUSTER_NEW 

- name: 'Create db home with name {{ db_home_name }}'
  oci_database_db_home:
    compartment_id: '{{ compartment_id }}'
    database_software_image_id: '{{ database_software_image_id }}'
    db_version: '{{ version }}'
    display_name: '{{ db_home_name }}'
    key_by: ['vm_cluster_id', 'display_name']
    kms_key_id: '{{ kms_key_id }}'
    kms_key_version_id: '{{ kms_key_version_id }}'
    source: '{{ db_home_source }}'
    vm_cluster_id: '{{ vm_cluster_id }}'
  register: 'db_home_create_result'
- debug:
    msg: '{{ db_home_create_result }}'
- set_fact:
    db_home_id: '{{ db_home_create_result.db_home.id }}'
    db_home_version: '{{ db_home_create_result.db_home.db_version }}'
    oracle_home: '{{ db_home_create_result.db_home.db_home_location }}'
    

- name: 'Patch DB Home to {{ ru_version }} if needed'
  include_tasks: 'db_patch.yml'
  when: db_home_version != ru_version