- name: ExaCS VM Cluster Discovery - VM Cluster Name
  oci_database_cloud_vm_cluster_facts:
    cloud_vm_cluster_id: '{{ vm_cluster_id }}'
  register: vm_cluster_discovery_result
- debug:
    msg: '{{ vm_cluster_discovery_result }}'
- set_fact: 
    compartment_id: '{{ vm_cluster_discovery_result.cloud_vm_clusters[0].compartment_id }}'
  when: vm_cluster_discovery_result.cloud_vm_clusters|length == 1