- name: 'Register Image {{ image_name }}'
  become: 'true'
  become_user: 'oracle'
  become_method: 'sudo'
  shell: |
    {{ rhpctl_path }} register image -image {{ image_name }} -getfromOSS {{ fpp_maps_path }}/{{ image_map }} -imagetype {{ software_type }}
  register: 'register_image_result'
- debug:
    msg: '{{ register_image_result }}'

