- name: 'Copy Bug List from Client to FPP'
  become: 'true'
  become_user: 'oracle'
  become_method: 'sudo'
  shell:  |
    scp -i {{ identity_file }} opc@{{ target_node }}:{{ exa_bugs_path }} {{ fpp_maps_path }}/{{ image_map_dir }}
  register: 'bugs_list_result'
- debug: { msg: '{{ bugs_list_result }}' }

- name: 'Use Template to create Map file {{ image_name }}.map'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  template:
    src: 'map.json'
    dest: '{{ fpp_maps_path }}/{{ image_map_dir }}/{{ image_name }}.map'
  register: 'map_template_result'
- debug: { msg: '{{ map_template_result }}' }