- name: 'Query Working Copy'
  become: 'true'
  become_user: 'oracle'
  become_method: 'sudo'
  shell: |
    {{ rhpctl_path }} query workingcopy -workingcopy {{ wc_name }} -details
  ignore_errors: '{{ ignore_errors_flag }}'
  register: 'query_wc_result'
- debug: { msg: '{{ query_wc_result }}' }

- block:
  - set_fact:
      curr_batch: '{{ query_wc_result.stdout | regex_findall("Current batch. (\[[^\]]*\])") | first }}'
  - debug: { var: curr_batch }
  when: query_wc_result.stdout | regex_search("Current batch")